name: Build and Push Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [order-service, inventory-service, payment-service, notification-service, nginx]
        include:
          - service: order-service
            context: ./order-service
            dockerfile: ./order-service/Dockerfile
          - service: inventory-service
            context: ./inventory-service
            dockerfile: ./inventory-service/Dockerfile
          - service: payment-service
            context: ./payment-service
            dockerfile: ./payment-service/Dockerfile
          - service: notification-service
            context: ./notification-service
            dockerfile: ./notification-service/Dockerfile
          - service: nginx
            context: ./nginx
            dockerfile: ./nginx/Dockerfile

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push ${{ matrix.service }}
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.context }}
        file: ${{ matrix.dockerfile }}
        push: true
        platforms: linux/amd64,linux/arm64          # important error resolved by adding this line   ||| Error: no matching manifest for linux/arm64/v8
        tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Replace DOCKER_USERNAME in manifests
      run: |
        find k8s -name "*.yml" -type f -exec sed -i '' "s/DOCKER_USERNAME/${{ secrets.DOCKER_USERNAME }}/g" {} \;
    
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/
    
    - name: Restart deployments to pull latest images
      run: |
        kubectl rollout restart deployment/order-service
        kubectl rollout restart deployment/inventory-service
        kubectl rollout restart deployment/payment-service
        kubectl rollout restart deployment/notification-service
        kubectl rollout restart deployment/nginx-gateway
    
    - name: Wait for rollout to complete
      run: |
        kubectl rollout status deployment/order-service
        kubectl rollout status deployment/inventory-service
        kubectl rollout status deployment/payment-service
        kubectl rollout status deployment/notification-service
        kubectl rollout status deployment/nginx-gateway
